## Sample Data

Looking at one of the data files...

In [1]:
import pandas as pd
from shapely.geometry import Point, LineString

from bokeh.palettes import Sunset10
from bokeh.io import output_notebook, show
from bokeh.plotting import figure

Read the CSV files exported from the XLS Files sandbox (`xls_files.ipynb`)
* `measurements.csv` has coordinates of line segments
* `points.csv` has coordinates of loci

Rename the colums with shorter, single-word names, and assign an index based on a column with unique IDs.

In [2]:
mf = pd.read_csv('measurements.csv', names=['X','Y','Name'], index_col='Name', header=0)

In [3]:
mf.head()

              X           Y
Name
A     38.500999  141.542007
B     39.457001  120.559998
C     40.560001  110.825996
D     43.907001   99.404999
E     48.821999   81.403999

In [4]:
foci = pd.read_csv('points.csv', names=["X","Y","Z","Unit","Category","Collection","Name","Surpass","Time","ID"
], index_col='ID', header=0)

In [5]:
foci.head()

,X,Y,Z,Unit,Category,Collection,Name,Surpass,Time
ID,,,,,,,,,
625,12.206000,76.806000,6.700,µm,Surface,Position,NaN,prg1_lp,1
416,12.059000,111.939003,7.067,µm,Surface,Position,NaN,prg1_dk,1
559,20.632999,51.368999,6.178,µm,Surface,Position,NaN,prg1_mp,1
671,69.564003,24.504000,5.614,µm,Surface,Position,NaN,prg1_tz,1
446,36.141998,24.242001,6.636,µm,Surface,Position,NaN,prg1_ep,1

In [6]:
mf.index

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
       'O', 'P', 'Q'],
      dtype='str', name='Name')

In [7]:
mf.loc['A']

X     38.500999
Y    141.542007
Name: A, dtype: float64

In [8]:
dct = {}
for i, label in enumerate(mf.index[:-1]):
    head = mf.index[i]
    tail = mf.index[i+1]
    k = head+tail
    p0 = Point(mf.loc[head].X, mf.loc[head].Y)
    p1 = Point(mf.loc[tail].X, mf.loc[tail].Y)
    dct[k] = LineString([p0,p1])

In [9]:
dct

{'AB': <LINESTRING (38.501 141.542, 39.457 120.56)>,
 'BC': <LINESTRING (39.457 120.56, 40.56 110.826)>,
 'CD': <LINESTRING (40.56 110.826, 43.907 99.405)>,
 'DE': <LINESTRING (43.907 99.405, 48.822 81.404)>,
 'EF': <LINESTRING (48.822 81.404, 54.427 66.404)>,
 'FG': <LINESTRING (54.427 66.404, 61.472 53.318)>,
 'GH': <LINESTRING (61.472 53.318, 67.041 44.591)>,
 'HI': <LINESTRING (67.041 44.591, 72.587 25.798)>,
 'IJ': <LINESTRING (72.587 25.798, 69.01 14.931)>,
 'JK': <LINESTRING (69.01 14.931, 61.052 11.458)>,
 'KL': <LINESTRING (61.052 11.458, 50.432 11.52)>,
 'LM': <LINESTRING (50.432 11.52, 45.424 19.481)>,
 'MN': <LINESTRING (45.424 19.481, 41.883 26.756)>,
 'NO': <LINESTRING (41.883 26.756, 36.718 37.509)>,
 'OP': <LINESTRING (36.718 37.509, 23.646 69.875)>,
 'PQ': <LINESTRING (23.646 69.875, 17.912 91.123)>}

Distance from foci to first line segment

In [10]:
f0 = Point(foci.loc[625].X, foci.loc[625].Y)
f0.distance(dct['AB'])

51.54638053985944

### Bokeh Plots

In [11]:
output_notebook()

Static plot with marker labels

In [12]:
p = figure(title='germline', x_axis_label='x', y_axis_label='y')
p.line(x='X', y='Y', source=mf)
p.scatter(x='X', y='Y', size=5, source=mf)
p.text(x='X', y='Y', text='Name', x_offset=5, y_offset=10, source=mf)
show(p)

Plot first few foci and line segments

In [13]:
N = 10    # number of foci to show; use len(foci) to show all of them 

yellow = Sunset10[5]

p = figure(title='germline', x_axis_label='x', y_axis_label='y')
p.line(x='X', y='Y', source=mf)
p.scatter(x='X', y='Y', size=5, source=mf)
p.scatter(x='X', y='Y', size=8, fill_color=yellow, source=foci.head(N))
show(p)